#!/bin/sh

input="$1"
output="$2"

# This only works for pngs
# mencoder mf://*.png -mf fps=1 -o output.avi -ovc xvid -xvidencopts bitrate=1600

mencoder "mf://${input}" -mf fps="${fps}" -o "${output}" -ovc xvid -xvidencopts bitrate=1600
